# matrix:
#   include:
#     # works on Precise and Trusty
#     - os: linux
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-4.9
#       env:
#          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

#     # works on Precise and Trusty
#     - os: linux
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-5
#       env:
#          - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

#     # works on Precise and Trusty
#     - os: linux
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-6
#       env:
#         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

#     # works on Precise and Trusty
#     - os: linux
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-7
#       env:
#         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

# before_install:
#     - eval "${MATRIX_EVAL}"



# install: make get-deps
# ./configure && make && make test
# language: c
# script: scons
before_install:
  - sudo apt-get install check
language: c
script: make && make test
# sudo: false # only for faster builds
# script:
#   -  -coverage -O0 hello.c -o hello
#   - ./hello


# after_success:
#   - bash <(curl -s https://codecov.io/bash)
